language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
after_success:
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - "mvn deploy --settings target/travis/settings.xml"

branches:
  except:
    - travis

env:
  global:
    - secure: "FyED8+ODtJ+Oe7gtGcH/cvNF7gWny1GkgCL8+mitd6u9lILnk9q8YU5PSgo5\n8fjUAqq7TgfXXFdd9i2XPkK3VRWzz3jfQc36SRsy58QjwgmzRul92Yxzn/n0\nwT5uWgTXCwCHcEWI7lGYzqWSxHOpSvCg0ykPirz0BJpNIl03YFQ="
    - secure: "OyzhcHghVDTrS4meslvDN6MGZ09G+kjeOUHHZkRyuLQy8gIWtnYb2gR3KFE/\ntzKDkfOxAiLWiOQy6XwC5mSXMB/TzGkLm4lNg90PTxGJ/5huwB+wnA8enbNl\nVjS5q9e1ZHvptsHrQXijM4UU9Fj9rHYtxrvmc65yWRH2nSiAgH4="
